blueye:
  controller_node:
    ros__parameters:
      inputRelativePosition: dummy_position
      outputThrusterForce: thruster_force_norm_ref #cmd_vel 
      outputSlowGainRef: slow_gain_ref
      inputPose: pose
      starting_position: [18.0, 11.0, 0.20]
      limit_left: 18.0
      limit_right: 4.3
      limit_depth: 1.9
      x_discretization: 13 #26
      depth_discretization: 3
      tolerance: 0.15
      depth_tolerance: 0.1
      slow_gain_ref: 1.0
      max_thrust_pos: 1.0
      max_thrust_neg: -1.0